from contextlib import contextmanager
from contextvars import ContextVar
from dataclasses import dataclass
import os
from pathlib import Path
import shutil
import signal
import socket
import sys
import subprocess
import time
from typing import Iterator, List, Optional, Sequence, TextIO
import warnings

import psutil
from dotenv import dotenv_values
from dotenv.variables import parse_variables
from termcolor import colored

from .constants import DEFAULT_META_DIR, META_SUFFIX, ON_WINDOWS
from .results import CommandSnapshot, TaskSnapshot
from .types import DmonTaskConfig, DmonMeta, PathType, ProcessIdentity
from .utils import len_ansi, pad_ansi


_builtin_print = print
_diagnostic_stream: ContextVar[Optional[TextIO]] = ContextVar(
    "dmon_diagnostic_stream", default=None
)


def print(*values, **kwargs) -> None:
    stream = _diagnostic_stream.get()
    if stream is not None and kwargs.get("file") is sys.stderr:
        kwargs["file"] = stream
    _builtin_print(*values, **kwargs)


@contextmanager
def diagnostic_output(stream: TextIO) -> Iterator[None]:
    token = _diagnostic_stream.set(stream)
    try:
        yield
    finally:
        _diagnostic_stream.reset(token)


@dataclass(frozen=True)
class StartResult:
    exit_code: int
    meta: Optional[DmonMeta] = None
    error: str = ""


def background_process_kwargs() -> dict:
    if ON_WINDOWS:
        return {"creationflags": 0x08000000}  # CREATE_NO_WINDOW
    return {"start_new_session": True}


def ensure_meta_dir(meta_path: Path):
    """
    Ensure the meta directory exists.
    If it is under the default meta directory, create .gitignore to ignore all files in it.
    """
    meta_dir = meta_path.resolve().parent
    meta_dir.mkdir(parents=True, exist_ok=True)
    if meta_dir == DEFAULT_META_DIR.resolve():
        gitignore = DEFAULT_META_DIR / ".gitignore"
        if not gitignore.exists():
            gitignore.write_text("# Auto-generated by dmon\n*\n")


def ensure_log_dir(log_path: Path):
    log_path.parent.mkdir(parents=True, exist_ok=True)


def start(cfgs: Sequence[DmonTaskConfig]):
    ret = 0
    failed = []
    for idx, cfg in enumerate(cfgs):
        result = start_single(cfg)
        ret |= result
        if result:
            failed.append(cfg.task)
        if idx < len(cfgs) - 1:
            print("---", file=sys.stderr)  # print a blank line between tasks
    if failed and len(cfgs) > 1:
        succeeded = len(cfgs) - len(failed)
        failed_tasks = ", ".join(
            colored(f"'{task}'", color="cyan", attrs=["bold"]) for task in failed
        )
        print(
            f"\nStarted {succeeded} task(s); failed to start: {failed_tasks}. "
            "Multi-task start is best-effort, so successful tasks were left running.",
            file=sys.stderr,
        )
    return ret


def start_single(cfg: DmonTaskConfig) -> int:
    return start_single_result(cfg).exit_code


def start_single_result(cfg: DmonTaskConfig) -> StartResult:
    # Python 3.8 on Windows may leave resolve() relative if a parent is missing.
    # Anchor before resolving so newly created records have durable locations.
    meta_path = Path(cfg.meta_path).absolute().resolve()
    log_path = Path(cfg.log_path).absolute().resolve()
    cwd = Path(cfg.cwd).resolve()

    try:
        existing_meta = DmonMeta.load(meta_path)
    except (OSError, ValueError, TypeError) as error:
        print(
            colored(
                f"Start failed: cannot read metadata {meta_path}: {error}",
                color="red",
                attrs=["bold"],
            ),
            file=sys.stderr,
        )
        return StartResult(1, error=f"cannot read metadata {meta_path}: {error}")
    if existing_meta and existing_meta.state == "starting":
        print(
            colored(
                f"Start failed: task '{cfg.task}' is already being started by another dmon process.",
                color="red",
                attrs=["bold"],
            ),
            file=sys.stderr,
        )
        print(
            "If the earlier start was interrupted, run 'dmon stop' to remove its reservation.",
            file=sys.stderr,
        )
        return StartResult(1, error="task is already being started")
    if existing_meta and check_running(existing_meta.pid, existing_meta.create_time):
        print(
            f"{colored('Start failed: meta file already exists', color='red', attrs=['bold'])}",
            file=sys.stderr,
        )
        print_status(existing_meta)
        print(
            "\nRun 'dmon status' / 'dmon list' to check, or 'dmon stop' to stop it.",
            file=sys.stderr,
        )
        return StartResult(1, error="task is already running")
    if existing_meta:
        if any(
            check_running(child.pid, child.create_time)
            for child in existing_meta.descendants
        ) or unverified_group_remains(existing_meta):
            print(
                f"Start failed: task '{cfg.task}' still has residual processes; "
                "stop its owning stack or inspect its preserved metadata first.",
                file=sys.stderr,
            )
            return StartResult(1, error="task still has residual processes")
        print(
            colored(
                f"Removing stale metadata for exited task '{cfg.task}'.",
                color="yellow",
            ),
            file=sys.stderr,
        )
        meta_path.unlink(missing_ok=True)

    ensure_meta_dir(meta_path)
    ensure_log_dir(log_path)

    try:
        env = task_environment(cfg)
    except (OSError, ValueError) as error:
        print(
            colored(
                f"Start failed for task '{cfg.task}': {error}",
                color="red",
                attrs=["bold"],
            ),
            file=sys.stderr,
        )
        # Detailed environment diagnostics belong in the log, not persisted state.
        return StartResult(1, error="environment setup failed; see startup diagnostics")

    shell = isinstance(cfg.cmd, str)

    # Platform-specific parameters to run the process in background detached from parent
    kwargs = background_process_kwargs()
    command = cfg.cmd
    if ON_WINDOWS:
        if isinstance(command, list) and len(command) > 0:
            # On Windows, use full path for the executable when shell=False
            command = [shutil.which(command[0]) or command[0], *command[1:]]

    meta = DmonMeta(
        task=cfg.task,
        state="starting",
        meta_path=str(meta_path),
        log_path=str(log_path),
        log_rotate=cfg.log_rotate,
        cmd=cfg.cmd,
        cwd=str(cwd),
        override_env=cfg.override_env,
        shell=shell,
        popen_kwargs=kwargs,
    )

    try:
        meta.dump(meta_path, exclusive=True)
    except FileExistsError:
        print(
            colored(
                f"Start failed: another dmon process is starting task '{cfg.task}'.",
                color="red",
                attrs=["bold"],
            ),
            file=sys.stderr,
        )
        return StartResult(1, error="another dmon process is starting this task")

    try:
        if cfg.log_rotate:
            rotate_log_path = Path(cfg.rotate_log_path).absolute().resolve()

            meta.rotate_log_path = str(rotate_log_path)
            meta.log_max_size = cfg.log_max_size
            meta.log_backup_count = cfg.log_backup_count
            meta.rotate_log_max_size = cfg.rotate_log_max_size
            meta.rotate_log_backup_count = cfg.rotate_log_backup_count

            ensure_log_dir(rotate_log_path)

            # use runner to start user process and handle log rotation
            if isinstance(command, str):
                # Transport shell text as one argument. Splitting and joining
                # would discard quotes, escapes, and significant whitespace.
                cmd = [command]
            else:
                cmd = command
            args = [
                sys.executable,
                "-m",
                "dmon.runner",
                "--log-path",
                str(log_path),
                "--max-log-size",
                str(cfg.log_max_size),
                "--rotate-log-path",
                str(rotate_log_path),
                "--max-rotate-log-size",
                str(cfg.rotate_log_max_size),
            ]
            if cfg.log_backup_count is not None:
                args.extend(["--log-backup-count", str(cfg.log_backup_count)])
            if cfg.rotate_log_backup_count is not None:
                args.extend(
                    ["--rotate-log-backup-count", str(cfg.rotate_log_backup_count)]
                )
            if shell:
                args.append("--shell")
            args.append("--")
            args.extend(cmd)
            proc = subprocess.Popen(
                args,
                cwd=cwd,
                env=env,
                stdout=subprocess.DEVNULL,
                stderr=subprocess.STDOUT,
                **kwargs,
            )
        else:
            # Open the log file (append binary mode)
            with open(log_path, "ab", buffering=0) as lof:
                # Start the child process with stdout/stderr redirected to the log
                proc = subprocess.Popen(
                    command,
                    stdout=lof,
                    stderr=subprocess.STDOUT,
                    cwd=cwd,
                    env=env,
                    shell=shell,
                    text=False,  # binary mode
                    bufsize=0,  # unbuffered
                    **kwargs,
                )
    except OSError as error:
        meta_path.unlink(missing_ok=True)
        detail = str(error)
        if not error.filename and isinstance(cfg.cmd, list):
            # CreateProcess may omit the filename. Keep the executable useful
            # for diagnostics without copying potentially sensitive arguments.
            detail = f"command {cfg.cmd[0]!r}: {detail}"
        if (
            isinstance(error, FileNotFoundError)
            and cfg.override_env
            and env is not None
            and "PATH" not in env
            and cwd.is_dir()
        ):
            detail += (
                "; override_env=true removes the inherited environment, including PATH. "
                "Use env without override_env for variable overrides, or supply PATH explicitly."
            )
        print(
            colored(
                f"Start failed for task '{cfg.task}': {detail}",
                color="red",
                attrs=["bold"],
            ),
            file=sys.stderr,
        )
        return StartResult(1, error=detail)

    meta.pid = proc.pid
    meta.state = "running"
    try:
        p = psutil.Process(proc.pid)
        create_time = p.create_time()
        create_time_human = time.strftime(
            "%Y-%m-%d %H:%M:%S", time.localtime(create_time)
        )
        meta.create_time = create_time
        meta.create_time_human = create_time_human
    except (psutil.NoSuchProcess, ValueError):
        # process already exited?
        pass

    try:
        meta.dump(meta_path)
    except OSError as error:
        try:
            managed_process = psutil.Process(proc.pid)
        except psutil.NoSuchProcess:
            pass
        else:
            terminate_process(managed_process, timeout=2.0)
        meta_path.unlink(missing_ok=True)
        print(
            colored(
                f"Start failed: cannot save metadata for task '{cfg.task}': {error}",
                color="red",
                attrs=["bold"],
            ),
            file=sys.stderr,
        )
        return StartResult(1, error=f"cannot save metadata: {error}")

    print_status(meta)
    with warnings.catch_warnings():
        warnings.simplefilter("ignore", ResourceWarning)
        del proc
    return StartResult(0, meta)


def task_environment(cfg: DmonTaskConfig):
    file_env = {}
    for value in cfg.env_files:
        path = Path(value).resolve()
        if not path.is_file():
            raise FileNotFoundError(
                f"environment file not found for task '{cfg.task}': {path}"
            )
        parsed = dotenv_values(path, encoding="utf-8", interpolate=False)
        missing = [key for key, item in parsed.items() if item is None]
        if missing:
            names = ", ".join(sorted(missing))
            raise ValueError(
                f"environment file for task '{cfg.task}' contains keys without "
                f"values: {names}"
            )
        inherited = {} if cfg.override_env else os.environ
        resolved = {}
        for key, item in parsed.items():
            assert item is not None
            context = {**inherited, **file_env, **resolved}
            resolved[key] = "".join(
                atom.resolve(context) for atom in parse_variables(item)
            )
        file_env.update(resolved)
    if cfg.override_env:
        return {**file_env, **cfg.env}
    if file_env or cfg.env:
        return {**file_env, **os.environ, **cfg.env}
    return None


def stop(meta_paths: Sequence[PathType], timeout=5.0):
    ret = 0
    for idx, meta_path in enumerate(meta_paths):
        # non-zero if any stop() fails
        ret |= stop_single(meta_path=meta_path, timeout=timeout)
        if idx < len(meta_paths) - 1:
            print(file=sys.stderr)  # print a blank line between tasks
    return ret


def stop_single(
    meta_path: PathType,
    timeout=5.0,
):
    meta_path = Path(meta_path).resolve()
    try:
        meta = DmonMeta.load(meta_path)
    except (OSError, ValueError, TypeError) as error:
        print(
            colored(
                f"Stop failed: cannot read metadata {meta_path}: {error}",
                color="red",
                attrs=["bold"],
            ),
            file=sys.stderr,
        )
        return 1
    if meta is None:
        print(
            colored(
                "Stop failed: meta file not found (maybe not started)\n",
                color="red",
                attrs=["bold"],
            )
            + str(meta_path),
            file=sys.stderr,
        )
        return 1

    pid = meta.pid
    try:
        proc = psutil.Process(pid)
    except (psutil.NoSuchProcess, ValueError):
        if stop_owned_processes(meta, timeout):
            return 1
        print(
            colored(
                f"Process {pid} not found (already exited); removing stale meta file",
                color="yellow",
                attrs=["bold"],
            ),
            file=sys.stderr,
        )
        print_status(meta)
        meta_path.unlink(missing_ok=True)
        return 0

    # check if it's the same process by comparing create_time
    if not check_same_process(proc, meta.create_time):
        if stop_owned_processes(meta, timeout):
            return 1
        print(
            colored(
                f"Warning: PID {pid} exists but create_time does not match (maybe reused by another process); removing stale meta file",
                color="yellow",
                attrs=["bold"],
            ),
            file=sys.stderr,
        )
        print_status(meta)
        meta_path.unlink(missing_ok=True)
        return 0
    if not process_is_alive(proc):
        if stop_owned_processes(meta, timeout):
            return 1
        print(
            colored(
                f"Process {pid} already exited; removing stale meta file",
                color="yellow",
                attrs=["bold"],
            ),
            file=sys.stderr,
        )
        print_status(meta)
        meta_path.unlink(missing_ok=True)
        return 0

    refresh_descendants(meta)
    ret = stop_owned_processes(meta, timeout)
    print_status(meta)
    if ret == 0:
        meta_path.unlink(missing_ok=True)
    return ret


def owned_identities(meta: DmonMeta) -> List[ProcessIdentity]:
    identities = list(meta.descendants)
    if meta.pid > 0 and meta.create_time >= 0:
        identities.insert(0, ProcessIdentity(meta.pid, meta.create_time))
    return identities


def refresh_descendants(meta: DmonMeta) -> bool:
    """Retain observed live identities, even after their parent has exited.

    This is ancestry evidence within the user's trust domain, not a security
    boundary. Children that escape before observation cannot be recovered by
    guessing from names, ports or process group numbers.
    """
    observed = set()
    for identity in owned_identities(meta):
        process = get_unique_process(identity.pid, identity.create_time)
        if process is None:
            continue
        if identity.pid != meta.pid:
            observed.add(identity)
        try:
            children = process.children(recursive=True)
            if not check_same_process(process, identity.create_time):
                continue
            for child in children:
                if process_is_alive(child):
                    observed.add(ProcessIdentity(child.pid, child.create_time()))
        except (psutil.NoSuchProcess, psutil.AccessDenied):
            continue
    descendants = sorted(observed, key=lambda item: (item.pid, item.create_time))
    changed = descendants != meta.descendants
    meta.descendants = descendants
    return changed


def task_owns_listener(meta: DmonMeta, host: str, port: int) -> bool:
    """Positive evidence only; unavailable process sockets never imply ownership.

    Callers validate a literal loopback endpoint. Never inspect or signal a
    foreign listener, and never treat a successful network probe as identity.
    """
    root = get_unique_process(meta.pid, meta.create_time)
    if root is None:
        return False
    try:
        processes = [root, *root.children(recursive=True)]
        for process in processes:
            try:
                birth = process.create_time()
                for connection in process.net_connections(kind="tcp"):
                    if (
                        connection.status == psutil.CONN_LISTEN
                        and connection.laddr.port == port
                        and (
                            connection.laddr.ip == host
                            or connection.laddr.ip
                            == (
                                "::"
                                if connection.family == socket.AF_INET6
                                else "0.0.0.0"
                            )
                            and (
                                (":" in host) == (connection.family == socket.AF_INET6)
                            )
                        )
                        and check_running(process.pid, birth)
                        and check_running(meta.pid, meta.create_time)
                    ):
                        return True
            except (psutil.NoSuchProcess, psutil.AccessDenied):
                continue
    except (psutil.NoSuchProcess, psutil.AccessDenied):
        pass
    return False


def stop_owned_processes(meta: DmonMeta, timeout: float) -> int:
    """Stop verified identities; preserve evidence when cleanup is uncertain."""
    failed = False
    for identity in owned_identities(meta):
        process = get_unique_process(identity.pid, identity.create_time)
        if process is not None and terminate_process(process, timeout):
            failed = True
    if unverified_group_remains(meta):
        print(
            f"Task '{meta.task}' exited but its former process group still has "
            "unverified members; refusing to signal them. Metadata was preserved.",
            file=sys.stderr,
        )
        failed = True
    return int(failed)


def unverified_group_remains(meta: DmonMeta) -> bool:
    if ON_WINDOWS or meta.pid <= 0 or not meta.popen_kwargs.get("start_new_session"):
        return False
    try:
        if not check_same_process(psutil.Process(meta.pid), meta.create_time):
            return False  # A recycled group leader is not ours.
    except (psutil.NoSuchProcess, ValueError):
        pass
    return process_group_exists(meta.pid)


def terminate_process(proc: psutil.Process, timeout: float) -> int:
    if not ON_WINDOWS:
        try:
            process_group = os.getpgid(proc.pid)
        except (ProcessLookupError, psutil.NoSuchProcess):
            return 0
        if process_group == proc.pid:
            return terminate_posix_group(proc, process_group, timeout)
    return terminate_process_tree(proc, timeout)


def terminate_posix_group(
    proc: psutil.Process, process_group: int, timeout: float
) -> int:
    try:
        os.killpg(process_group, signal.SIGTERM)
    except ProcessLookupError:
        return 0

    deadline = time.monotonic() + timeout
    while time.monotonic() < deadline and process_group_exists(process_group):
        try:
            proc.wait(timeout=0)
        except (psutil.NoSuchProcess, psutil.TimeoutExpired):
            pass
        time.sleep(0.05)
    if process_group_exists(process_group):
        print(
            colored(
                f"Process group {process_group} did not exit in time; killing it",
                color="yellow",
                attrs=["bold"],
            ),
            file=sys.stderr,
        )
        try:
            os.killpg(process_group, signal.SIGKILL)
        except ProcessLookupError:
            return 0
        except PermissionError:
            if process_group_exists(process_group):
                return 1
    try:
        proc.wait(timeout=1)
    except (psutil.NoSuchProcess, psutil.TimeoutExpired):
        pass
    print(
        colored(
            f"Process group {process_group} stopped; removing meta file",
            color="green",
            attrs=["bold"],
        ),
        file=sys.stderr,
    )
    return 0


def process_group_exists(process_group: int) -> bool:
    for process in psutil.process_iter(["pid", "status"]):
        if process.info["status"] == psutil.STATUS_ZOMBIE:
            continue
        try:
            if os.getpgid(process.info["pid"]) == process_group:
                return True
        except (OSError, psutil.NoSuchProcess):
            continue
    return False


def terminate_process_tree(proc: psutil.Process, timeout: float) -> int:
    try:
        processes = [*proc.children(recursive=True), proc]
    except psutil.NoSuchProcess:
        return 0
    for process in reversed(processes):
        try:
            process.terminate()
        except psutil.NoSuchProcess:
            pass
    _, alive = psutil.wait_procs(processes, timeout=timeout)
    for process in alive:
        try:
            process.kill()
        except psutil.NoSuchProcess:
            pass
    _, alive = psutil.wait_procs(alive, timeout=1)
    if alive:
        print(
            colored(
                "Failed to stop process tree: "
                + ", ".join(str(process.pid) for process in alive),
                color="red",
                attrs=["bold"],
            ),
            file=sys.stderr,
        )
        return 1
    print(
        colored(
            f"Process tree {proc.pid} stopped; removing meta file",
            color="green",
            attrs=["bold"],
        ),
        file=sys.stderr,
    )
    return 0


def restart(
    cfgs: Sequence[DmonTaskConfig],
    timeout=5.0,
):
    meta_paths = [cfg.meta_path for cfg in cfgs]
    stop(meta_paths, timeout=timeout)
    print("--- Restarting ---", file=sys.stderr)
    return start(cfgs)


def status(meta_paths: Sequence[PathType]):
    ret = 0
    snapshots = []
    for idx, meta_path in enumerate(meta_paths):
        meta_path = Path(meta_path).resolve()
        try:
            meta = DmonMeta.load(meta_path)
        except (OSError, ValueError, TypeError) as error:
            print(
                colored(
                    f"Status failed: cannot read metadata {meta_path}: {error}",
                    color="red",
                    attrs=["bold"],
                ),
                file=sys.stderr,
            )
            ret |= 1
            if idx < len(meta_paths) - 1:
                print("---", file=sys.stderr)
            continue
        if meta is None:
            print(
                colored(
                    "Status failed: meta file not found (maybe not started)\n",
                    color="red",
                    attrs=["bold"],
                )
                + str(meta_path),
                file=sys.stderr,
            )
            ret |= 1
        else:
            snapshot = task_snapshot(meta)
            print_task_status(snapshot)
            snapshots.append(snapshot)
            if not snapshot.running:
                ret |= 1
        if idx < len(meta_paths) - 1:
            print("---", file=sys.stderr)
    if snapshots:
        print("\nProcess Tree:", file=sys.stderr)
        print_task_table(snapshots)
    return ret


def check_same_process(proc: psutil.Process, create_time: float) -> bool:
    if create_time < 0:
        return False
    return abs(proc.create_time() - create_time) < 1e-3


def process_is_alive(proc: psutil.Process) -> bool:
    try:
        return proc.is_running() and proc.status() != psutil.STATUS_ZOMBIE
    except psutil.NoSuchProcess:
        return False


def get_unique_process(pid: int, create_time: float):
    """
    Get the process with given PID and create_time if it is still the same process.
    """
    if create_time >= 0:
        try:
            p = psutil.Process(pid)
            if check_same_process(p, create_time) and process_is_alive(p):
                return p
        except psutil.NoSuchProcess:
            pass
    return None


def check_running(pid: int, create_time: float) -> bool:
    """
    Check if a process with given PID and create_time is running.
    """
    # return psutil.pid_exists(pid)
    if create_time < 0:
        return False
    try:
        p = psutil.Process(pid)
        return check_same_process(p, create_time) and process_is_alive(p)
    except psutil.NoSuchProcess:
        return False


def task_snapshot(meta: DmonMeta) -> TaskSnapshot:
    command: CommandSnapshot = (
        tuple(meta.cmd) if isinstance(meta.cmd, list) else meta.cmd
    )
    return TaskSnapshot(
        task=meta.task,
        pid=meta.pid,
        status=("running" if check_running(meta.pid, meta.create_time) else "exited"),
        command=command,
        working_directory=meta.cwd,
        create_time=meta.create_time,
        create_time_human=meta.create_time_human,
        meta_path=meta.meta_path,
        log_rotate=meta.log_rotate,
        log_path=meta.log_path,
        rotate_log_path=meta.rotate_log_path,
        log_max_size=meta.log_max_size,
        log_backup_count=meta.log_backup_count,
        rotate_log_max_size=meta.rotate_log_max_size,
        rotate_log_backup_count=meta.rotate_log_backup_count,
        live_descendant_pids=tuple(
            identity.pid
            for identity in meta.descendants
            if check_running(identity.pid, identity.create_time)
        ),
    )


def display_command(command: CommandSnapshot):
    return list(command) if isinstance(command, tuple) else command


def print_status(meta: DmonMeta):
    print_task_status(task_snapshot(meta))


def print_task_status(snapshot: TaskSnapshot) -> None:
    status = (
        colored("Running", on_color="on_green")
        if snapshot.running
        else colored("Exited", on_color="on_light_red")
    )

    # key-value pairs with aligned keys
    rows = [
        ("TASK", colored(snapshot.task, "cyan", attrs=["bold"])),
        ("PID", colored(str(snapshot.pid), "cyan", attrs=["bold"])),
        ("STATUS", status),
        ("CMD", display_command(snapshot.command)),
        ("WORKING DIR", snapshot.working_directory),
        ("CREATE TIME", snapshot.create_time_human),
        ("META PATH", snapshot.meta_path),
        ("LOG ROTATE", snapshot.log_rotate),
        ("LOG PATH", snapshot.log_path),
    ]
    if snapshot.log_rotate:
        rows.append(("ROTATE LOG PATH", snapshot.rotate_log_path))
        rows.append(("LOG MAX SIZE", f"{snapshot.log_max_size} MB"))
        if snapshot.log_backup_count is not None:
            rows.append(("LOG BACKUP COUNT", snapshot.log_backup_count))
        rows.append(("ROTATE LOG MAX SIZE", f"{snapshot.rotate_log_max_size} MB"))
        if snapshot.rotate_log_backup_count is not None:
            rows.append(("ROTATE LOG BACKUP COUNT", snapshot.rotate_log_backup_count))

    # calculate the max width of the keys
    key_width = max(len(key) for key, _ in rows)
    # align the keys and print
    lines = [
        f"{colored(f'{key:<{key_width}}: ', attrs=['dark'])}{value}"
        for key, value in rows
    ]
    print("\n".join(lines), file=sys.stderr)


def get_table_row(p: psutil.Process, target_ppid: int, prefix=""):
    ppid = p.ppid()
    ppid_str = (
        colored(str(ppid), "cyan", attrs=["bold"]) if ppid == target_ppid else str(ppid)
    )
    return (
        prefix + p.name(),
        p.pid,
        ppid_str,
        p.status(),
        p.cmdline(),
        time.strftime("%Y-%m-%d %H:%M:%S", time.localtime(p.create_time())),
        "N/A",
    )


def print_process_table(metas: List[DmonMeta], full_width: bool = False):
    return print_task_table([task_snapshot(meta) for meta in metas], full_width)


def print_task_table(snapshots: Sequence[TaskSnapshot], full_width: bool = False):
    headers = ("TASK", "PID", "PPID", "STATUS", "CMD", "CREATE TIME", "LOG PATH")
    align = ("<", ">", ">", "<", "<", "<", "<")

    # add table header
    rows = []
    rows.append(headers)

    processes = []
    for snapshot in snapshots:
        proc = get_unique_process(snapshot.pid, snapshot.create_time)
        if proc:
            status = colored("Running", on_color="on_green")
            ppid = proc.ppid()
            processes.append(proc)
        else:
            status = colored("Exited", on_color="on_light_red")
            ppid = "N/A"
        rows.append(
            (
                colored(snapshot.task, "cyan", attrs=["bold"]),
                colored(snapshot.pid, "cyan", attrs=["bold"]),
                ppid,
                status,
                display_command(snapshot.command),
                snapshot.create_time_human,
                snapshot.log_path,
            )
        )
        # add child processes indented
        if proc:
            children = proc.children(recursive=True)
            for idx, child in enumerate(children):
                prefix = "├ " if idx < len(children) - 1 else "└ "
                rows.append(get_table_row(child, target_ppid=proc.pid, prefix=prefix))
                processes.append(child)

    # calculate column widths
    widths = [max(len_ansi(str(row[i])) for row in rows) for i in range(len(headers))]

    term_width = shutil.get_terminal_size().columns
    diff = sum(widths) + 2 * (len(headers) - 1) - term_width
    if diff > 0 and not full_width:
        # truncate CMD column
        cmd_idx = headers.index("CMD")
        widths[cmd_idx] = max(widths[cmd_idx] - diff, 10)  # at least 10 chars

    # print the table with proper padding
    lines = []
    for row in rows:
        line = "  ".join(
            # pad the cell except the last one if left-aligned (no need for extra spaces)
            (
                pad_ansi(str(cell), widths[i], align[i])
                if i < len(align) - 1 or align[i] != "<"
                else str(cell)
            )
            for i, cell in enumerate(row)
        )
        lines.append(line)
    print("\n".join(lines), file=sys.stderr)

    return processes


def get_meta_paths(dir: PathType) -> List[Path]:
    target_dmon_dir = Path(dir).resolve()
    meta_paths: List[Path] = []
    if target_dmon_dir.exists() and target_dmon_dir.is_dir():
        for meta_file in target_dmon_dir.glob(f"*{META_SUFFIX}"):
            meta_paths.append(meta_file)
    return meta_paths


def list_processes(dir: PathType, full_width: bool):
    target_dmon_dir = Path(dir).resolve()
    meta_paths = get_meta_paths(target_dmon_dir)
    snapshots = []
    errors = 0
    for meta_path in meta_paths:
        try:
            meta = DmonMeta.load(meta_path)
        except (OSError, ValueError, TypeError) as error:
            print(
                colored(
                    f"Cannot read metadata {meta_path}: {error}",
                    color="red",
                    attrs=["bold"],
                ),
                file=sys.stderr,
            )
            errors += 1
            continue
        if meta is not None:
            snapshots.append(task_snapshot(meta))
    # sort by name (case-insensitive)
    snapshots.sort(key=lambda item: item.task.lower())
    n_task = len(snapshots)
    processes = print_task_table(snapshots, full_width)
    n_proc = len(processes)
    print(
        f"\nFound {n_task} task{'s' if n_task > 1 else ''} ({n_proc} process{'es' if n_proc > 1 else ''}) in {target_dmon_dir}",
        file=sys.stderr,
    )
    return 1 if errors else 0


def execute(cfg: DmonTaskConfig):
    """
    Execute the command in the foreground.
    This is used for the 'dmon exec' command.
    """
    cwd = Path(cfg.cwd).resolve()

    try:
        env = task_environment(cfg)
    except (OSError, ValueError) as error:
        print(
            colored(
                f"Exec failed for task '{cfg.task}': {error}",
                color="red",
                attrs=["bold"],
            ),
            file=sys.stderr,
        )
        return 1

    shell = isinstance(cfg.cmd, str)
    if ON_WINDOWS and isinstance(cfg.cmd, list) and len(cfg.cmd) > 0:
        # On Windows, use full path for the executable when shell=False
        cfg.cmd[0] = shutil.which(cfg.cmd[0]) or cfg.cmd[0]

    proc = subprocess.Popen(
        cfg.cmd,
        cwd=cwd,
        env=env,
        shell=shell,
        bufsize=0,  # unbuffered
        close_fds=False,
    )

    def signal_handler(signum: int, frame) -> None:
        # POSIX terminals deliver SIGINT to both foreground processes. Forwarding
        # it would make the child receive Ctrl-C twice. Windows needs explicit
        # forwarding, translated to a signal subprocess can deliver reliably.
        if not ON_WINDOWS and signum == signal.SIGINT:
            return
        if ON_WINDOWS and signum == signal.SIGINT:
            signum = signal.SIGTERM
        try:
            proc.send_signal(signum)
        except ProcessLookupError:
            pass

    prev_handle_int = signal.signal(signal.SIGINT, signal_handler)
    prev_handle_term = signal.signal(signal.SIGTERM, signal_handler)
    try:
        return proc.wait()
    finally:
        signal.signal(signal.SIGTERM, prev_handle_term)
        signal.signal(signal.SIGINT, prev_handle_int)
